#!/bin/bash
#
# Easy MySQL backup shell.
#
# Fork me on github:
#  http://github.com/seirei/mysql-link-dump
#
# Author:
#   MORI Tomohito <seirei@me.com>
#   Copyright 2013, no rights reserved.
#

#
# source env.
#
READ_LINK=`readlink $0`
ENV_FILE=`dirname $READ_LINK`/envvars
source $ENV_FILE

#
# Setting.
#
DB_NAME=`basename $0`

#
# Backup MySql.
#
mysqldump -h $DB_HOST -u $DB_USER -p$DB_PASS $DB_NAME | gzip > $BACKUP_DIR/$BACKUP_FILE
